
export enum LocalStorageKey {
    // APP
    CURRENT_EXPERIENCE_ID = "#::|_-KxK-_|::#",
    CURRENT_EXPERIENCE_KEY = "#::|_-ExE-_|::#",

    CURRENT_EVENT_ID = "#::|_-SxS-_|::#",
    CURRENT_EVENT_PUBLISH_AT = "#::|_-PxP-_|::#",
    PUBLICATION_CALLBACK_SAVE = "#::|_-CxC-_|::#",

    DEVICES_CALLBACK_SAVE = "#::|_-IxI-_|::#",

    REFUND_ASKING_CALLBACK_SAVE = "#::|_-DxD-_|::#",
    CURRENT_RESERVATION = "#::|_-RxR-_|::#",
    ASK_DIRECT_REFUNDING_FOR = "#::|_-DRxDR-_|::#",

    LOADER_ON_SWITCH = '#::|_-SSxSS-_|::#',
    EXP_BOOKING_REQUEST_ID = '#::|_-BRxBR-_|::#',

    USER_WHO_MAKE_RESERVATION_REQUEST_ID = '#::|_-USxUS-_|::#',

    APP_PREVIOUS_URL = '#:a|_RTY5&7',
    APP_CURRENT_URL = '#:a|540Y&7',

    // AUTH
    CURRENT_USER = "E_|_X_|_E",
    CURRENT_USER_PRELOAD = "E_|_(.)_|_E",

    ACCESS_TOKEN = "E_|_V_|_E",
    REFRESH_TOKEN = "E_|_H_|_E",

    KEEP_CONNECT = "E_|_K_|_E",
    LAST_ACTION_LINK = "E_|_S_|_E",

    CONNEXION_DATA = "E_|_Y_|_E",
    SELLER_MODE = "E_|_SM_|_E",

    BUYER_MODE = "E_|_BM_|_E",
    CONFIRM_AUTH_DATA = "E_|_QP_|_E",

    MODE_SESSION = "E_|_AT_|_E",
    USER_HAS_SELLER = "E_|_HS_|_E",


    // SETTING
    VERIFICATION_COUNT_REACHED_FOR_MAIL_CHANGE = "S_M_T_P_P",
    VERIFICATION_COUNT_REACHED_FOR_MAIL_PASSWORD_CHANGE = "S_Z_N_C_L",

    VERIFICATION_COUNT_REACHED_FOR_MAIL_REBOOT_PASSWORD = "S_N_D_Q_V",
    VERIFICATION_COUNT_REACHED_FOR_MAIL_DOUBLE_AUTH = "S_E_Z_O_A",

    VERIFICATION_COUNT_REACHED_FOR_MAIL_TELEPHONE_CHANGE = "S_H_D_N_Z",
    VERIFICATION_COUNT_REACHED_FOR_MAIL_ACCOUNT_DISABLING = "S_W_T_U_M",

    VERIFICATION_COUNT_REACHED_FOR_MAIL_NEW_DEVICE_CONNEXION = "S_R_B_X_J",
    VERIFICATION_COUNT_REACHED_FOR_MAIL_CANCEL_EXPERIENCE = "S_S_W_Z_U",

    VERIFICATION_COUNT_REACHED_FOR_MAIL_CANCEL_EVENT = "S_Q_L_C_B",
    VERIFICATION_COUNT_REACHED_FOR_MAIL_CLOSE_EVENT = "S_Y_R_E_V",

    VERIFICATION_COUNT_REACHED_FOR_MAIL_CLOSE_EXPERIENCE = "S_L_N_X_X",
    VERIFICATION_COUNT_REACHED_FOR_MAIL_WITHDRAW_AMOUNT = "S_T_T_Z_U",
    VERIFICATION_COUNT_REACHED_FOR_MAIL_PASS_PROCESS = "S_A_A_V_W",

    SAVE_EVENT_THUMBNAIL_URL_FILE = "Y_A_Q_V_B_P",
    SAVE_EXPERIENCE_THUMBNAIL_URL_FILE = "Y_E_S_E_B_P"
}